FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_APPWRITE_ENDPOINT
ARG VITE_APPWRITE_PROJECT_ID
ARG VITE_APPWRITE_PARSE_INVOICE_FUNCTION_ID
ARG VITE_APPWRITE_AI_ASSISTANT_FUNCTION_ID

ENV VITE_APPWRITE_ENDPOINT=$VITE_APPWRITE_ENDPOINT
ENV VITE_APPWRITE_PROJECT_ID=$VITE_APPWRITE_PROJECT_ID
ENV VITE_APPWRITE_PARSE_INVOICE_FUNCTION_ID=$VITE_APPWRITE_PARSE_INVOICE_FUNCTION_ID
ENV VITE_APPWRITE_AI_ASSISTANT_FUNCTION_ID=$VITE_APPWRITE_AI_ASSISTANT_FUNCTION_ID

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY deployment/nginx/msme-pilot.conf /etc/nginx/conf.d/default.conf
RUN sed -i 's#/var/www/msme-pilot/current#/usr/share/nginx/html#g' /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
